---
functional:
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность удалять товар из корзины
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - На странице товара и в каталоге должно выводиться название, рейтинг, цена со скидкой и без нее
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен быть SPA-приложение, которое не перезагружает страницу
  - Сайт должен иметь постраничный вывод товара
  - Оформление заказа должно происходить с переходом на страницу оплаты
non-functional:
  - Сайт должен иметь мобильную версию
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть доступен для пользователей без использования VPN (прямой доступ из сети Интернет)
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - На странице товара и в каталоге должно выводиться название, рейтинг, цена со скидкой и без нее
implicit:
  - Система должна отображать статус наличия товара (в наличии/нет в наличии) на странице товара и в корзине. 
  - При попытке добавить отсутствующий товар система должна блокировать действие и информировать пользователя о недоступности позиции.
  - Товар в корзине должен сохраняться при завершении сессии
  - При отсутствии результатов поиска по заданному запросу система должна отображать информативное сообщение об отсутствии товаров и предлагать альтернативные варианты (похожие товары, другие категории, корректировку запроса).
  - Система должна поддерживать комбинирование фильтров (выбор нескольких значений в одном фильтре и нескольких разных фильтров одновременно). При отсутствии товаров, соответствующих выбранным фильтрам, система должна отображать сообщение об отсутствии результатов и предлагать сбросить фильтры или скорректировать критерии.
  - Мобильная версия сайта должна корректно отображаться и обеспечивать полную функциональность на устройствах с различными разрешениями экрана, форм-факторами и операционными системами (iOS, Android).
  - При переключении языка интерефейсы, должна коректно отображаться верстка сайта, выбраннеый язык должен сохраняться для профиля пользователя и не должен переключаться после завершения сессии
